server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    h2:
      console:
        enabled: true
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: "e-commerce"
  app:
    jwt-expiration-ms: 30000000
    jwt-secret: TB2eOxdG+mX3YVYmVsVrxQkSz8JfEV6v9CsktZp2EqU=


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:

